stages:
    - debug
    - release
    - deliver
    - trigger

debug:
    stage: debug
    script:
        - ./build debug
    except:
         - master

release:
    stage: release
    script:
        - ./build release
    except:
        - master

delivery:
    stage: deliver
    variables:
        MIU_PATH: "/opt/staging/miu"
        INC_PATH: "$MIU_PATH/include"
        DBG_PATH: "$MIU_PATH/lib-dbg"
        REL_PATH: "$MIU_PATH/lib-rel"
        BIN_PATH: "$MIU_PATH/binaries"
        UT_PATH: "$MIU_PATH/unittest"
    script:
        - ./build debug
        - ./build release

        - mkdir -p $INC_PATH
        - rm -fr $INC_PATH/mkt
        - cp -frv ./include/mkt $INC_PATH

        - mkdir -p $DBG_PATH
        - cp -fv debug/libmkt.a $DBG_PATH
        - cp -fv debug/libmktsvc.a $DBG_PATH

        - mkdir -p $REL_PATH
        - cp -fv release/libmkt.a $REL_PATH
        - cp -fv release/libmktsvc.a $REL_PATH

        - mkdir -p $UT_PATH
        - cp -fv release/ut_mkt $UT_PATH

    only:
        - master

testmkt:
    stage: trigger
    script:
        - curl -X POST -F token=c0b3646ef27206e1dca3ccd72bdb28 -F mkt=master $GITLAB_URL/api/v4/projects/19/trigger/pipeline"
    only:
        - master

mktview:
    stage: trigger
    script:
        - curl -X POST -F token=30a0dd87601a58d49e9a23ff36bdb4 -F mkt=master $GITLAB_URL/api/v4/projects/20/trigger/pipeline"
    only:
        - master
